### ISSUE TITLE
gunicorn might be worth a test as webserver for the check

### ISSUE THREAD

**Issue by darix** [Oneiroi/clustercheck#13]
works nicely for python webapps for me.

(just read the blog post on https://www.percona.com/blog/2014/05/16/benchmark-simplehttpserver-vs-pyclustercheck-twisted-implementation/ )

**Comment by Oneiroi** [comment]
Hi @darix,

Thanks for the suggestion, the only reason for using the original SimpleHTTPServer is the fact it's "built in" and therefore already present on most distributions.

As per the blog post however the twisted implementation is much more per-formant, the caveat used to be that twisted was not available to some distributions without adding extra repositories, this appears to be changing in more recent distros.

This post compares a number of python wsgi servers http://nichol.as/benchmark-of-python-web-servers and may also be of interest.
