### ISSUE TITLE
--cache-time option causes pyclustercheck to fail

### ISSUE THREAD

**Issue by UnixRonin** [Oneiroi/clustercheck#16]
I've been working on creating an init script to use with pyclustercheck, since it seems much better than the regular clustercheck (not dependent on xinetd, can use a .my.cnf file, single persistent process instead of constant spawns, ...)

During this process I discovered that setting the --cache-time option to any non-default value caused pyclustercheck to always report that the node is not synced, even when it very clearly is.  Unfortunately I do not know Python and can't immediately see why this is failing.

**Comment by Oneiroi** [comment]
Should be resolved in #18 please raise another issue if this is not the case.
