### ISSUE TITLE
Which License is used for this software ?

### ISSUE THREAD

**Issue by samitani** [Oneiroi/clustercheck#17]
I would like to use your software in my company. This soft seems to be OSS. Which License ? Could you add License description?

**Comment by Oneiroi** [comment]
Fixed added GNUv3 here: https://github.com/Oneiroi/clustercheck/blob/master/LICENSE

**Comment by samitani** [comment]
@Oneiroi Let me confirm.
GPLv3 and AGPL is different. your lisence file is AGPL.  is it correct ?
I prefer GPLv3.

**Comment by Oneiroi** [comment]
Let me prefix my comment here with: I.A.N.A.L (I am Not A Lawyer). Can you please state why you prefer GPLv3 over AGPL ?

**Comment by samitani** [comment]
@Oneiroi thank you for reply.

AGLv3 is stronger "copy left" license than GPLv3. AGPLv3 requires to publish source code to who access my product via network. GPLv3 not requires that.

It is risks for the company which does not want to publish their (customized) source code. So, my company prohibit using AGPLv3 software. This is reason why I prefer GPLv3.

this is my problem. You can chose License which you want.
