### ISSUE TITLE
Create a semver git tag (eg. 0.1.0)

### ISSUE THREAD

**Issue by toabctl** [Oneiroi/clustercheck#28]
I would like to upload an sdist tarball to pypi, but the current versioning is not PEP440 compatible.
The failure is:
```
HTTPError: 400 Client Error: '0.1.dev59+ge476caf' is an invalid value for Version. Error: Can't use PEP 440 local versions. See https://packaging.python.org/specifications/core-metadata for url: https://upload.pypi.org/legacy/
``` 

Uploading a `0.1.0` git tag would change the version that `setuptools_scm` calculates

**Comment by toabctl** [comment]
cc @Oneiroi

**Comment by Oneiroi** [comment]
https://github.com/Oneiroi/clustercheck/releases/tag/0.1.0

**Comment by Oneiroi** [comment]
closing issue as resolved.
